services:
  - type: web
    name: packaging-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    workingDir: server
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: packaging-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    workingDir: client
    plan: free
